/**
 * Emits the SQL that backfills `runs` from the run directories on disk (Step 3.1).
 *
 * Writes SQL to stdout rather than connecting to Postgres itself, deliberately:
 *  - it needs no service-role secret, so it is safe to run anywhere, and
 *  - you can read exactly what is about to be written before anything is applied.
 *
 * Usage:
 *   npx tsx scripts/generateRunBackfill.ts > backfill.sql     # inspect, then apply
 *   npx tsx scripts/generateRunBackfill.ts --summary          # counts only, no SQL
 *
 * Diagnostics go to stderr so `> backfill.sql` captures only SQL.
 *
 * Re-running is safe: every INSERT is `on conflict (id) do nothing`, so this can be run again
 * whenever new runs have accumulated without touching rows that already exist.
 */

import { allRunIds, summariseRun } from "../src/runStore.js";

/** Must match the bootstrap migration's organisation id, and auth.ts's LOCAL_USER_ID. */
const DEFAULT_ORG_ID = "00000000-0000-4000-8000-000000000010";
const LOCAL_USER_ID = "00000000-0000-4000-8000-000000000001";

/** Postgres string literal. Doubling single quotes is the only escape a dollar-free literal needs. */
function sql(value: string | null): string {
  if (value === null) return "NULL";
  return `'${value.replace(/'/g, "''")}'`;
}

function main(): void {
  const summaryOnly = process.argv.includes("--summary");
  const ids = allRunIds();

  const rows: string[] = [];
  const skipped: { runId: string; reason: string }[] = [];

  for (const runId of ids) {
    // One malformed directory (an interrupted run, a partial write) must never abort the batch —
    // that is TD-17's "one bad record poisons everything" failure in a new place. Skip, record
    // why, keep going.
    try {
      const s = summariseRun(runId);
      const startedAt = Number.isFinite(s.startedAt) && s.startedAt > 0
        ? new Date(s.startedAt).toISOString()
        : null;

      rows.push(
        `  (${sql(s.runId)}, ${sql(DEFAULT_ORG_ID)}, NULL, ${sql(LOCAL_USER_ID)}, ` +
        `${sql(s.prompt || null)}, ${sql(s.url || null)}, ${sql(s.status)}, ` +
        `${startedAt ? sql(startedAt) : "NULL"}::timestamptz, ${sql(`runs/${s.runId}`)})`,
      );
    } catch (err) {
      skipped.push({ runId, reason: (err as Error)?.message ?? String(err) });
    }
  }

  console.error(`[backfill] run directories found: ${ids.length}`);
  console.error(`[backfill] rows generated:        ${rows.length}`);
  console.error(`[backfill] skipped (malformed):   ${skipped.length}`);
  for (const s of skipped) console.error(`[backfill]   SKIP ${s.runId}: ${s.reason}`);

  if (summaryOnly) return;
  if (rows.length === 0) {
    console.error("[backfill] nothing to emit.");
    return;
  }

  console.log("-- Generated by scripts/generateRunBackfill.ts (implentationplan.md Step 3.1).");
  console.log(`-- ${rows.length} of ${ids.length} run directories; ${skipped.length} skipped.`);
  console.log(
    "insert into runs (id, organisation_id, project_id, started_by, prompt, url, status, started_at, artifact_path) values",
  );
  console.log(rows.join(",\n"));
  console.log("on conflict (id) do nothing;");
}

main();
