-- An optional hand-written Playwright script that REPLACES the generated one for a case.
--
-- Why a separate column rather than reusing `test_case_versions.spec`:
--
-- `spec` means "the generated spec for this version's ir, cached at save time". Its whole
-- contract (see getCaseScript in src/server/library.ts) is that regenerating from `ir` is an
-- equivalent source, not a degraded one -- generateSpec is pure and deterministic (DECISIONS.md
-- D-06), so stored and regenerated bytes are interchangeable, and a null `spec` is simply
-- re-derived on read.
--
-- An override breaks exactly that equivalence: the stored script is NOT derivable from `ir`.
-- Storing it in `spec` would make the existing null-fallback silently serve a different script
-- from the one that actually runs. So `spec` keeps its meaning untouched, and an override lives
-- in its own column behind an explicit boolean -- never inferred from "is this column non-null",
-- so the two states can never be ambiguous.
--
-- `ir` stays NOT NULL and keeps being written on an override: it remains the last known
-- description of intent, it is what the case reverts TO, and it is what the steps panel renders
-- (while stating that it no longer describes what runs).

alter table public.test_case_versions
  add column if not exists script_override text,
  add column if not exists script_overridden boolean not null default false;

-- Mirrored onto test_cases for the same reason `ir` and `current_version` already are: the replay
-- loader (loadCasesForReplay) selects from test_cases in one query and must know whether to run
-- the override without a second round trip per case. test_case_versions remains the history.
alter table public.test_cases
  add column if not exists script_override text,
  add column if not exists script_overridden boolean not null default false;

comment on column public.test_case_versions.script_overridden is
  'True when this version runs script_override instead of a spec generated from ir. Explicit flag, never inferred from script_override being non-null.';

comment on column public.test_case_versions.script_override is
  'Hand-written Playwright spec that replaces the generated one. Not grounded: no locator in it is verified against a discovered element. Only meaningful when script_overridden is true.';

comment on column public.test_cases.script_overridden is
  'Mirror of the current version''s script_overridden, denormalised for the replay loader.';

comment on column public.test_cases.script_override is
  'Mirror of the current version''s script_override, denormalised for the replay loader.';
